PLANETS = {
    "солнце": "Sun",
    "sun": "Sun",
    "меркурий": "Mercury",
    "mercury": "Mercury",
    "венера": "Venus",
    "venus": "Venus",
    "земля": "Earth",
    "earth": "Earth",
    "луна": "Moon",
    "moon": "Moon",
    "марс": "Mars",
    "mars": "Mars",
    "юпитер": "Jupiter",
    "jupiter": "Jupiter",
    "сатурн": "Saturn",
    "saturn": "Saturn",
    "уран": "Uranus",
    "uranus": "Uranus",
    "нептун": "Neptune",
    "neptune": "Neptune",
    "плутон": "Pluto",
    "pluto": "Pluto",
}
